site_name: Anthro Docs
theme:
  logo: anthro-logo-400x400.jpg
  favicon: anthro-logo-400x400.jpg
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.footer
  - navigation.indexes
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  locale: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: grey
      accent: red
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.betterem
  - attr_list

nav:
  - Home: index.md
  - Getting Started: #Introduce the project
    - Mission: getting started/mission.md #Welcome page for the project
    - Roles & Positions: getting started/roles & positions.md
    - Tasks:  getting started/tasks.md
  - Requirements: #Outline requirements for the project
    - Overview: requirements/requirements and guidelines overview.md #Overview of requirements and guidelines 
    - Accessibility: requirements/accessibility requirements.md
    - Design: requirements/design requirements.md
    - Hardware: requirements/hardware requirements.md
    - Software: requirements/software requirements.md
    - SI: requirements/synthetic intelligence requirements.md
    - Version Control: requirements/version control.md
  - Roadmap: #Roadmap of the project.
    - Goals: roadmap/project goals.md #Overview of the project's goals
    - Scope: roadmap/project scope.md
    - Timeline: roadmap/project timeline.md
  - Progress Tracker: #Tracker for various sections of the project
    - Hardware: progress tracker/hardware progress.md
    - Software: progress tracker/software progress.md
    - SI: progress tracker/synthetic intelligence progress.md
    - Design & Aesthetics: progress tracker/design and aesthetics progress.md
    - Media & Marketing: progress tracker/media and marketing progress.md
    - Recruitment: progress tracker/recruitment progress.md
  - Links: links.md #Links to relevant project pages
  - Contact: contact.md #contact information

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/anthrobo
      name: Anthrobo on X
    - icon: fontawesome/brands/github
      link: https://github.com/Anthrobotics
      name: Anthrobotics GitHub
  generator: false
copyright: Copyright &copy; 2024 <a href="https://anthrobotics.ca" target="_blank" rel="noopener">Anthrobotics</a>
