site_name: Anthro Docs
theme:
  logo: anthro-logo-400x400.jpg
  favicon: anthro-logo-400x400.jpg
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.footer
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  locale: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: grey
      accent: red
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.betterem
  - attr_list

nav:
  - Home:
    - index.md
  - Getting Started: #Introduce the project
    - getting started/0 mission.md #Welcome page for the project
    - getting started/1 roles & positions.md
    - getting started/2 tasks.md
  - Requirements: #Outline requirements for the project
    - requirements/0 requirements and guidelines overview.md #Overview of requirements and guidelines 
    - requirements/1 accessibility requirements.md
    - requirements/2 design requirements.md
    - requirements/3 hardware requirements.md
    - requirements/4 software requirements.md
    - requirements/5 synthetic intelligence requirements.md
    - requirements/6 version control.md
  - Roadmap: #Roadmap of the project.
    - roadmap/0 project goals.md #Overview of the project's goals
    - roadmap/1 project scope.md
    - roadmap/2 project timeline.md
  - Progress Tracker: #Tracker for various sections of the project
    - progress tracker/0 hardware progress.md
    - progress tracker/1 software progress.md
    - progress tracker/2 synthetic intelligence progress.md
    - progress tracker/3 design and aesthetics progress.md
    - progress tracker/4 media and marketing progress.md
    - progress tracker/5 recruitment progress.md
  - Links: #Links to relevant project pages
    - links/0 links.md
  - Contact: #contact information
    - contact/0 contact.md


extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/anthrobo
      name: Anthrobo on X
    - icon: fontawesome/brands/github
      link: https://github.com/Anthrobotics
      name: Anthrobotics GitHub
  generator: false
copyright: Copyright &copy; 2024 <a href="https://anthrobotics.ca" target="_blank" rel="noopener">Anthrobotics</a>
